### ISSUE TITLE
Week 1: INDIVIDUAL:: NOTES + QUIZZES + CORRECTIONS

### ISSUE THREAD

**Issue by ranand2445** [sarayu-pr11/team-avatar#17]
1.3 + 1.4

**Comment by Abigail-Peltz** [comment]
Word of the day/Vocabulary based learning
SAT/ACT Prep work/test reviews
Study Timer
Study Hall with studying tips
Random joke/prompt/etc. generator
Music recommendation generator
Interactive online worksheets
Safety presentation/safety page
Mini-Slideshow of our about me pages
A way to animate the page changes
Decorating the backgrounds with gifs or other images
Coming up with either one or two website themes
